Settings vibration
jeyjey626/neuropathy-app pull request #41
Opened 2023-06-09 17:23 UTC by jeyjey626

2023-06-11 08:34 UTC, s174508 requested changes
Bugs:
- I get an off-by-one bug when doing the following:
 1. Tap "Vibration duration" in settings menu
 2. Tap "+" or "-"
 3. Tap "Start"
 4. (Optional: Tap "Stop")
 5. Tap the opposite of what you did in 2. (to go back to initial value)
 6. Now, displayed value is as expected, but internal value is probably the value from 2.
 7. (Optional: Tap "Start" and notice that vibration button uses the value from 2.)
 8. Press "Confirm"
 9. Saved value is the value from 2.
- Saved value isn't applied to vibration test

Suggestions (up for discussion):
- Set an upper limit on number of seconds
- Stop vibrating when user changes duration value
- Allow pressing confirm even if value is unchanged

2023-06-11 08:34 UTC, s174508 commented on assets/lang/da.json
> +            "text": "dk Vibration is used in the vibration test. On different models of phones, how long the phone can vibrate may differ. Adjust the duration of the vibration to fit your phone, and
```suggestion
            "text": "Vibration bruges til vibrationstesten. Hvor længe mobilen kan vibrere, kan afhænge af modellen. Juster varigheden af vibrationen så den passer til din mobil, og test at knappen nedenunder virker."
```

2023-06-11 10:41 UTC, jeyjey626 commented
> Stop vibrating when user changes duration value

Stopping vibration when they change a value could be done, but should be best done with transforming it into a bloc element. This way vibration could also be stopped when a patient clicks an answer in the examination, #49 
It could be easier done with overriding `void rebuild()` but it is a shortcut. (won't work in the examination though.

The rest of the comments I will resolve:
> I get an off-by-one bug when doing the following:

Fixing
> Set an upper limit on number of seconds 

30 seems reasonable
> Allow pressing confirm even if value is unchanged

Yes.

2023-06-12 12:45 UTC, s174508 approved these changes

2023-06-12 12:46 UTC, merged